services:
  api:
    build:
      context: .
    container_name: api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
    env_file:
      - .env
    networks:
      - express-js-docker
  db:
    image: mongo
    container_name: db
    expose:
      - "27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data_dev:/data/db
      - mongo_configdb_dev:/data/configdb
    networks:
      - express-js-docker

networks:
  express-js-docker:
volumes:
  mongo_data_dev:
  mongo_configdb_dev:
