services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - express-js-docker
  db:
    image: mongo
    container_name: db
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    expose:
      - "27017"
    networks:
      - express-js-docker

networks:
  express-js-docker:
volumes:
  mongo_data:
  mongo_configdb:
